[versions]
otel = "1.42.0"
junit = "5.11.0"
jsonSchema = "1.5.0"
snakeyaml = "2.3"
assertj = "3.26.3"

[libraries]
otel-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "otel" }
otel-sdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "otel" }
otel-sdk-logs = { module = "io.opentelemetry:opentelemetry-sdk-logs", version.ref = "otel" }
otel-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "otel" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchema" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
